services:
  client:
    build:
      context: client
    volumes:
      - $PWD/client:/app/
    ports:
      - 3000:3000
    x-develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json

  cognito:
    image: jagregory/cognito-local:latest
    volumes:
      - $PWD/.cognito:/app/.cognito
    ports:
      - 9229:9229
